### ISSUE TITLE
Dependency Triage 

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#205]
In efforts to make foyer easier to install, we should audit what dependencies we are pulling in. Additionally, keeping dependencies light keeps us from being stuck when upstream doesn't want to support a newer python version. 

For these packages, we need to

1. Summarize what they do for us
1. Evaluate how supported they are/updated
1. Evaluate if we can implement this ourselves

- [ ] parmed
- [ ] networkx
- [ ] oset
 - [ ] six
 - [ ] openmm <7.3
 - [ ] plyplus
 - [ ] requests
 - [ ] lxml

Then we can talk about what we want to cut/implement ourselves moving forwards. This list also is not authoritative, but taken from https://github.com/mosdef-hub/foyer/blob/master/devtools/conda-recipe/meta.yaml so I would appreciate it if someone double check to make sure I didn't miss anything (or if something can be removed since its not used at all)

**Comment by ctk3b** [comment]
Drive by comments:

* `oset`
Everything you can do with `oset`, you can do with the built-in `OrderedDict`. It's just not quite as clean.

Alternatively, boltons has an `IndexedSet`, is better maintained and is on conda-forge: https://anaconda.org/conda-forge/boltons

* `requests`

This package is about as ubiquitous as it gets in the python community. Unless you want to remove the feature to pull forcefields via a URL, I think this should be easy enough to keep.

* `six`

Just drop python 2 support ;)

* `networkx`

Don't think there's a good way around this.

* `plyplus`

Might be possible to swap it out for something else but you do NOT want to build this yourself.

* `lxml` 

Might be possible to use the built-in xml module. Maybe check what openmm uses since that's the format we're working with.

**Comment by mattwthompson** [comment]
Of those, we've only encountered issues with `plyplus` - maybe others have also died but they see fine, at least for now.

Stripping the dependencies into "normal" and "dev" helps a lot - the basic requirements list isn't too bad (and will be one shorter when we formally stop caring about Python 2.7 😄)

**Comment by summeraz** [comment]
Echoing @ctk3b's comments. These are all pretty standard packages, minus `parmed` and `openmm` which we obviously need to keep, and `plyplus`. @mattwthompson outlined our need to migrate from `plyplus` in #172, and I think we should be able to just replace `plyplus` with `lark` which has a noarch package on conda-forge. I'll try to take a whack at implementing that change.

**Comment by mattwthompson** [comment]
> I'll try to take a whack at implementing that change

You are welcome to try, but four of us have tried to do this and gotten nowhere 🤣. I think we should try and work on it together as a codemonkey project.

**Comment by vyasr** [comment]
This probably isn't necessary since it's one of your smaller dependencies, but fwiw six is pretty light and could be directly included as e.g. a git submodule in your project.

**Comment by mattwthompson** [comment]
After #224 we seem to be in a better place with our deps:

* `parmed`
Can't really get away from these in the short term

* `networkx`
No impetus to change this, see some discussion in #209

* `oset`
Dropped in favor of built-in sets #231 

* `six`
Non-problematic

*  `openmm <7.3`
This will be the next major dependency to be dropped in favor of our new backend
* `plyplus`
Removed as a dependency #224 (this is the other major problem that started off this discussion)

* `requests`
Non-problematic
* `lxml`
Non-problematic
