### ISSUE TITLE
Applying foyer forcefield to a large system is slow--can we populate a system with a typed compound/structure?

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/foyer#322]
**A summary of the question or discussion topic.**
Currently, if I want to apply a forcefield to a large system, I define a compound and box and use mbuild.packing.fill_box() to create my system. Then I apply my forcefield to the system, but it would be more more efficient to type _one_ compound and then populate my system with a typed compound. How can I do this?
I have a (messy) example of a workflow here:
https://github.com/jennyfothergill/opv-sim-tutorial/blob/master/GAFF-verification.ipynb
@chrisjonesBSU and I have been working on this together, so I will pull him in here. :)

**Comment by mattwthompson** [comment]
This is not supported now but would be a nice feature! Internally, it does something similar - the default behavior is `FF.apply(..., use_residue_map=True)` and if there are separate residues, it will type the first residue of each name, store that result in a dictionary, and look up that result the next time  another residue of that name is hit instead of running the atom-typing. However, this only works with cleanly-structured compounds of discrete residues, and I don't think this works well now for connected systems like polymers. It would be worth looking into trying to hack in the residue template-based atom-typing routines of OpenMM and other libraries into here, to see if that's doable, since residues in biophysics are typically connected monomers.

Another potential feature could be what you originally proposed -  to pass in a pre-typed object and populate out of that template, instead of determining the types internally.

Could you do some benchmarks and see how the atom-typing time scales with system size? Or maybe just set a debug and print out `independent_residues` [here](_check_independent_residues) - I think that `_check_independent_residues` is probably returning `False`.

**Comment by jennyfothergill** [comment]
I'm not sure what you mean by 

> set a debug and print out independent_residues here - I think that _check_independent_residues is probably returning False

**Comment by jennyfothergill** [comment]
Chris did some benchmarking of the apply function in [opv-sim-tutorial.ipynb](https://github.com/chrisjonesBSU/opv-sim-tutorial/blob/master/opv-sim-tutorial.ipynb)
![Screen Shot 2020-03-02 at 11 54 09 AM](https://user-images.githubusercontent.com/39961845/75703185-91cc3200-5c7c-11ea-99b8-25570448734c.png)

**Comment by mattwthompson** [comment]
That's probably close enough to call it linear, looks like it's not using residue templating

By that I just meant edit the source code to print the variable, or doing `import pdb; pdb.set_trace()` to manually inspect it to see the value

**Comment by chrisjonesBSU** [comment]
> It would be worth looking into trying to hack in the residue template-based atom-typing routines of OpenMM and other libraries into here, to see if that's doable, since residues in biophysics are typically connected monomers.

> Another potential feature could be what you originally proposed - to pass in a pre-typed object and populate out of that template, instead of determining the types internally.

Any guesses/advice on which of these 2 routes would be the best to start with?

**Comment by jennyfothergill** [comment]
If we're trying to drop OpenMM as a dependency, would option 2 be better?

**Comment by mattwthompson** [comment]
They're actually somewhat independent, I don't think I The sticking point for typing polymers (particularly with charge assignment methods) is figuring out what to do at the bonds between monomers. This may be less of an issue for a CG system without charges, I'm not sure.

The second option doesn't really hinge on the issue of connected residues - you should be able to do it for a box of water, passing in the type mapping for one water and letting it proceed with parametrizing the rest. The second option is probably easier to implement since it focuses on the parametrization step and not on the atom-typing step. Then, maybe from there, we can go back and try to add the typing step back in.

> If we're trying to drop OpenMM as a dependency, would option 2 be better?

Yes - if we can find a way to delicately copy parameters from an inputted monomer into each of the other monomers, that would be the best.

**Comment by rmatsum836** [comment]
Just to confirm `independent_residues` is returning `True`, but `residue_map.keys` is empty.

**Comment by mattwthompson** [comment]
Hmm ... that should not be the case

**Comment by jennyfothergill** [comment]
Sorry I don't mean to be dense, but I still have no idea what you mean by
>Just to confirm independent_residues is returning True, but residue_map.keys is empty.

is this a thing that I pass into ff.apply() or what? 

OK, also if we're to make a typed compound and then fill the box, this is an idea for how I would try to do that, but it ends up not working: 
```import mbuild as mb
import foyer

compound = mb.load("P3HT_16.mol2")

# Load GAFF
GAFF = foyer.forcefields.load_GAFF()

# Use foyer to parameterize
parameterized_structure = GAFF.apply(compound, assert_dihedral_params=False)

typed_compound = mb.Compound()
typed_compound.from_parmed(parameterized_structure)
#print([p.name for p in typed_compound.particles()])```

The particles names in typed compound are not the types from parmed.
Where am I misunderstanding/what can I do differently?

**Comment by rmatsum836** [comment]
Sorry I'm not being very clear.  On `ff.apply()`, `use_residue_map` is a default argument that is true by default.  What this does is build up a dictionary of typed residues in your system, and copies this atom-type information to the other similar residues in the system.  This is done to save time in the atom typing process.

You can see how this is done [here](https://github.com/mosdef-hub/foyer/blob/4c3dd9af4d7a9ede5c2aa092ee63c06262aefb7b/foyer/forcefield.py#L586).  I added some debug tracers around this section of the code to check what was going on.  In your example, `independent_residues` in line 586 is returning True in your example.  But in line 596 the actual residue map has no keys.  I'm going to look into this a little more.

Regardless, I like your original proposed idea and we should discuss this tomorrow.

**Comment by rmatsum836** [comment]
> Just to confirm `independent_residues` is returning `True`, but `residue_map.keys` is empty.

I misspoke here.  What is going on is that the residues have no name so the residue value is `''`.

**Comment by rmatsum836** [comment]
![image](https://user-images.githubusercontent.com/25011342/75714296-12952900-5c91-11ea-8c19-8da04c0dd6d5.png)

This is the performance with `use_residue_map=False`

**Comment by jennyfothergill** [comment]
OK, I understand where the `use_residue_map` is coming from, thank you! :)

**Comment by jennyfothergill** [comment]
For my use case this problem is solved by the following solution:
```python
import foyer
import mbuild as mb

p3ht = mb.load("c1sccc1cCCCCCC", smiles=True)
p3ht.name = "p3ht"
box = mb.Box([10,10,10])
system_box = mb.packing.fill_box(p3ht, 10, box=box)
pmd_box = system_box.to_parmed(residues=[p3ht.name]) # alternatively, infer_residues=True also works
gaff = foyer.forcefields.load_GAFF()
typed_structure = gaff.apply(pmd_box) # use_residue_map is True by default
```
