### ISSUE TITLE
Missing atom types opls_798 <--> opls_899

### ISSUE THREAD

**Issue by iGulitch** [mosdef-hub/foyer#568]
Hi!

I noticed quite a huge gap in your [OPLS-AA xml data file](https://github.com/mosdef-hub/foyer/blob/main/foyer/forcefields/xml/oplsaa.xml) : atom types from `opls_798` to `opls_899` inclusively are missing. Consequently, all other relevant info is missing too.

May I ask why?

**Comment by CalCraven** [comment]
You may! So the origins of that file are ported from [Gromacs](https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/ffnonbonded.itp). We just converted over those files directly into our xml format. As you can see, they also don't have the same parameters. So that's where the "missing" types are found.

On a more broad scope, MoSDeF is not a forcefield repository. We contain within Foyer the OPLS and TRaPPE forcefields because we've converted them over and are able to reasonably test that the atomtypes properly work with a set of common molecules. But tools that can generally atomtype large systems tend to be flawed: molecule differences at the fine grained level can be quite tiny, such as variations in conformation. And there is a lot of best estimate that goes with matching a forcefield from literature to a molecule. A lot of the tools that market themselves as general atomtypers come with that generalization risk, and I personally do not trust. If you make your forcefield generalizeable, it might not work well for a specific instance. If you make your forcefield to specific, it will only work for the molecule that you developed the forcefield from, which defeats the purpose of a forcefield since you already have all of the data for that molecule of interest.

In this vein, we highly recommend that users of MoSDeF/Foyer test their own forcefields to validate that the parameters they're getting seem sensible. This "sensibility" is highly application dependent. 

We also hope to add tools to help make porting over your own forcefields into a MoSDeF format much more accessible, as I believe that's the largest weakness in the MoSDeF ecosystem at this point in time. Improving SMARTS syntax, allowing conversion of parameterized files created for other engines, such as GROMACS Top files and ITP files, and LAMMPS datafiles, would be a huge addition to these packages. We also hope to port over some of the much more standardized (and well tested) amino acid forcefields. 

Something I'm working on currently is creating an updated forcefield xml from the recently published paper [OPLS/2020 Force Field for Unsaturated Hydrocarbons, Alcohols, and Ethers](https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.3c06602).  But it's still local because I have yet to develop a family of molecules to test it on, and wouldn't want to add it to the package until I can be reasonably confident it atomtypes molecules as expected.


Hope that answers some general MoSDeF related questions for you, and gives you more insight on the current state of the packages. Keep the questions coming because they're a good resource for others to see what's going on with things.

**Comment by iGulitch** [comment]
@CalCraven , you may want to take a look at the [supplement](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_002.txt) of that [paper](https://pubs.acs.org/doi/10.1021/acs.jpcb.3c06602) that you referred me to. In particular, you can find the following inside :

```
800      800-899 reserved for QM/MM atoms - do not use - they
899      will be read from the Z-matrix file, not from here
```

this answers my original question :)
