### ISSUE TITLE
save hoomd_xml files

### ISSUE THREAD

**Issue by evanmiller326** [mosdef-hub/foyer#73]
In the ethane.py example it is possible to save .top and .gro files. It would be nice to save hoomd_xml, gsd and lammpsdata files as it is done in mbuild.

**Comment by summeraz** [comment]
In mBuild when saving as .hoomdxml, .gsd, and .lammpsdata the `save` function is calling internal `save_hoomdxml`, `save_gsd`, and `save_lammpsdata` writers that actually take a ParmEd structure as an argument rather than an mBuild Compound (this conversion is performed within mBuild prior to calling the individual writers).  So it should be easy to support saving ParmEd structures in these formats.  However, in the long term what we would like to do is to add the `save_hoomdxml`, `save_gsd`, and `save_lammpsdata` functions to ParmEd, so that ParmEd is handling all of the saving.  These are only incorporated into mBuild right now because ParmEd does not have writers for these file formats.  I'm sure @ctk3b has a vision for how we should handle this in the short term, but it might be time for us to work on actually adding these writers into ParmEd

**Comment by mikemhenry** [comment]
I think adding the writers into ParmEd makes the most sense long term but short term would it be easier to copy writing code from mbuild or import the mbuild `save_hoomdxml` function?

**Comment by summeraz** [comment]
My mistake, the functions are write_hoomdxml, write_gsd, and write_lammpsdata.

As @mikemhenry suggested, these can be imported by using:
from mbuild.formats.hoomdxml import write_hoomdxml
from mbuild.formats.gsdwriter import write_gsd
from mbuild.formats.lammpsdata import write_lammpsdata

These functions are not currently included in the mBuild documentation, but we have actually been working on updating the documentation today, so I can make sure that soon information is available for those functions so you will know what arguments to pass.

**Comment by mikemhenry** [comment]
Thanks! @evanmiller326 and I are presenting mbuild and foyer to our lab today and hoomd is pretty critical to our workflow.

**Comment by summeraz** [comment]
Okay for now then (since we won't have the docs updated for a bit) it would probably be best to look at the source code for mBuild (in the `formats` directory).  The writers are pretty well documented there, so that should give you an idea of what arguments you will need to pass to them.

**Comment by ctk3b** [comment]
I'm gonna close this now but for the record the straightforward way to access these writers is with [Compound.save](https://github.com/mosdef-hub/mbuild/blob/master/mbuild/compound.py#L523)

E.g.
```python
ethane.save('ethane.hoomdxml', forcefield_name='oplsaa')
ethane.save('ethane.hoomdxml', forcefield_files='my_ff.xml')
```
